# Generated by Django 6.0.6 on 2026-07-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_sysuser_is_active_alter_sysuser_is_staff_and_more'),
        ('system', '0002_role_permissions_alter_sysuser_is_active_and_more'),
    ]

    operations = [
    ]
