# Generated by Codex for the initial Django framework.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("code", models.CharField(max_length=64, unique=True, verbose_name="设备编号")),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                ("model", models.CharField(blank=True, max_length=100, verbose_name="设备型号")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("maintenance", "维护中"),
                        ],
                        default="offline",
                        max_length=20,
                        verbose_name="设备状态",
                    ),
                ),
                ("battery_level", models.PositiveSmallIntegerField(default=100, verbose_name="电量")),
                ("location", models.CharField(blank=True, max_length=200, verbose_name="当前位置")),
                ("last_online_at", models.DateTimeField(blank=True, null=True, verbose_name="最后在线时间")),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InspectionTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("name", models.CharField(max_length=120, verbose_name="任务名称")),
                ("area", models.CharField(blank=True, max_length=120, verbose_name="巡检区域")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0, verbose_name="进度")),
                ("planned_start_at", models.DateTimeField(blank=True, null=True, verbose_name="计划开始时间")),
                ("planned_end_at", models.DateTimeField(blank=True, null=True, verbose_name="计划结束时间")),
                ("description", models.TextField(blank=True, verbose_name="任务描述")),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspection_tasks",
                        to="inspection.device",
                        verbose_name="执行设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "巡检任务",
                "verbose_name_plural": "巡检任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
