# Generated by Django 5.0.8 on 2026-07-03 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_name",
                    models.CharField(max_length=100, verbose_name="航线名称"),
                ),
                (
                    "alert_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="告警时间"),
                ),
                (
                    "detect_type",
                    models.CharField(
                        choices=[
                            ("obstacle", "障碍物"),
                            ("defect", "缺陷"),
                            ("anomaly", "异常行为"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="检测类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="告警描述")),
                ("location", models.CharField(max_length=200, verbose_name="位置信息")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已解决"),
                            ("ignored", "已忽略"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inspection.inspectiontask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警记录",
                "verbose_name_plural": "告警记录",
                "db_table": "inspection_alert",
            },
        ),
    ]
